name: dependencies
description: "A new Flutter package project."
version: 0.0.1
homepage:
publish_to: 'none'

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: ">=1.17.0"

# Inserted the dependencies here because the app don't need to know about the dependencies of the commons
dependencies:
  flutter:
    sdk: flutter

  flutter_modular: ^6.3.4
  equatable: ^2.0.5
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

